spring:
  application:
    name: zookeeper-example
  cloud:
    config:
      enabled: false
    zookeeper:
      connect-string: 172.16.0.70:8581
      discovery:
        metadata:
          management.context-path: /foo
          health.path: /ping

management.context-path: /foo
endpoints.health.path: /ping

